### ISSUE TITLE
Demo site and store are offline

### ISSUE THREAD

**Issue by andybak** [django-leonardo/django-leonardo#127]

**Comment by michaelkuty** [comment]
Sorry but domains was changed, check the header

https://www.leonardo-cms.org/
https://packages.leonardo-cms.org/
https://demo.leonardo-cms.org/
https://store.leonardo-cms.org/

readme was updated, but is not merged yet see readme in develop branch

**Comment by andybak** [comment]
Hi, it's README.rst that needs fixing

**Comment by michaelkuty** [comment]
Please check develop branch https://github.com/django-leonardo/django-leonardo/tree/develop which waits to merge
