### ISSUE TITLE
Is anybody aware the Demo site is messed up?

### ISSUE THREAD

**Issue by rcooke** [django-leonardo/django-leonardo#182]
Trying to evaluate Leonardo for a project, but when I go to the Demo site the CSS seems to be missing or messed up.

https://demo.leonardo-cms.org/

At least I hope this is not how a typical Leonardo site is supposed to look...

Tested from Firefox ESR 45.4.0 under Debian 8.

**Comment by michaelkuty** [comment]
Demo site was fixed, but is long time without maintanance and you can checkout other sites which are listed here https://www.leonardo-cms.org/en/portfolio/
also my personal site is maked in leonardo https://michaelkuty.com

**Comment by rcooke** [comment]
Thanks!

Did you have a DNS problem with your site, or maybe the links in the docs are outdated?  When I tried your site - the same day I made this ticket - all I got were 404 errors.

I did look at a few other sites, but the "official" demo site has all the bells and whistles in one place so it is preferred.

Plus, whether or not its working could be construed as an indicator of this projects health.  I'm just setting up a Python Anywhere server to test drive Leonardo.  Any install guide updates?

**Comment by michaelkuty** [comment]
No, just use master branch and you could use our bootstrap site script, cookiecutter or django template see the bootstrap script https://github.com/django-leonardo/django-leonardo/blob/master/contrib/scripts/install_leonardo_dev.sh

**Comment by rcooke** [comment]
I think your missing a "develop" branch or label?  The _dev install script calls for it, I get this error:

```
Obtaining django-leonardo from git+https://github.com/django-leonardo/django-leonardo@develop#egg=django-leonardo
  Cloning https://github.com/django-leonardo/django-leonardo (to develop) to ./src/django-leonardo
  Could not find a tag or branch 'develop', assuming commit.

error: pathspec 'develop' did not match any file(s) known to git.

Command "git checkout -q develop" failed with error code 1 in /home/stpaulsajax/source/leonardo_venv/src/django-leonardo
```
