### ISSUE TITLE
Error during Installtion

### ISSUE THREAD

**Issue by mvmthecreator** [django-leonardo/django-leonardo#88]
```
venv/local/lib/python2.7/site-packages/django_pyscss/compiler.py", line 11, in <module>
from scss import Compiler, config
ImportError: cannot import name Compiler
```

**Comment by michaelkuty** [comment]
Hi, thanks for feedback, please can you describe how you did installed Leonardo ?

please try run this script

```
wget -O - https://github.com/django-leonardo/django-leonardo/raw/develop/contrib/scripts/install_leonardo_dev.sh | sh
```

this scripts works well for me

here is line https://github.com/Kronuz/pyScss/blob/master/scss/__init__.py#L56 where Compiler still lives in pyScss library

**Comment by mvmthecreator** [comment]
this works for me too, before i have installed it with curl command.

**Comment by michaelkuty** [comment]
Thanks for feedback !
